import React, { useEffect, useState } from "react";
import { Link, useParams } from "wouter";
import { getListingBySlug, formatPrice, type SampleListing } from "@/data/sampleListings";
import { fetchPublicListingBySlug, type PublicListing } from "@/lib/publicListings";
import { WORDMARK_PREFIX, WORDMARK_SUFFIX, PLATFORM_NAME } from "@/lib/copy";
import { ONBOARDING_URL } from "@/lib/config";

function ScoreChip({ label, score }: { label: string; score: number }) {
  const color =
    score >= 70 ? "bg-emerald-50 text-emerald-700 border-emerald-200" :
    score >= 45 ? "bg-amber-50 text-amber-700 border-amber-200" :
    "bg-red-50 text-red-700 border-red-200";
  return (
    <span className={`inline-flex items-center gap-1.5 px-3 py-1 rounded-full text-xs font-medium border ${color}`}>
      <span className="font-bold">{score}</span>
      <span className="font-normal opacity-80">{label}</span>
    </span>
  );
}

function LeadForm({ listing }: { listing: SampleListing }) {
  const [submitted, setSubmitted] = useState(false);
  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    setSubmitted(true);
  };
  if (submitted) {
    return (
      <div className="text-center py-8">
        <div className="text-4xl mb-3">✓</div>
        <p className="font-semibold text-ink">Request received!</p>
        <p className="text-sm text-muted mt-1">This is a demo — no data was saved.</p>
      </div>
    );
  }
  return (
    <form onSubmit={handleSubmit} className="flex flex-col gap-3">
      <div className="flex gap-3">
        <input required placeholder="First name" className="flex-1 h-11 px-3 rounded border border-border text-sm bg-warm-white focus:outline-none focus:border-ink" />
        <input required placeholder="Last name" className="flex-1 h-11 px-3 rounded border border-border text-sm bg-warm-white focus:outline-none focus:border-ink" />
      </div>
      <input required type="email" placeholder="Email address" className="h-11 px-3 rounded border border-border text-sm bg-warm-white focus:outline-none focus:border-ink" />
      <input placeholder="Phone (optional)" className="h-11 px-3 rounded border border-border text-sm bg-warm-white focus:outline-none focus:border-ink" />
      <button type="submit" className="h-12 bg-gold text-white font-semibold text-sm rounded hover:bg-gold/90 transition-colors">
        Request a Showing
      </button>
      <p className="text-center text-xs text-muted">
        Demo mode — sign up to capture real leads.{" "}
        <a href={ONBOARDING_URL} className="underline hover:text-ink">Get started →</a>
      </p>
    </form>
  );
}

function NotFound() {
  return (
    <div className="min-h-screen flex flex-col items-center justify-center bg-warm-white text-center px-6">
      <h1 className="text-3xl font-serif font-bold text-ink mb-4">Listing not found</h1>
      <p className="text-muted mb-8">This demo listing doesn't exist. Browse our examples instead.</p>
      <Link href="/#demo" className="h-11 px-6 bg-ink text-warm-white rounded font-medium text-sm flex items-center hover:bg-ink/90 transition-colors">
        ← Browse examples
      </Link>
    </div>
  );
}

export default function Listing() {
  const params = useParams<{ slug: string }>();
  const slug = params.slug ?? "";
  const staticListing = getListingBySlug(slug);

  const [apiListing, setApiListing] = useState<PublicListing | null>(null);
  const [apiLoading, setApiLoading] = useState(!staticListing);

  useEffect(() => {
    if (staticListing) return;
    let cancelled = false;
    fetchPublicListingBySlug(slug).then((row) => {
      if (cancelled) return;
      setApiListing(row);
      setApiLoading(false);
    });
    return () => {
      cancelled = true;
    };
  }, [slug, staticListing]);

  const listing: (SampleListing & { photoUrls?: string[] }) | null =
    staticListing ?? apiListing;

  if (apiLoading) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-warm-white text-muted text-sm">
        Loading listing…
      </div>
    );
  }

  if (!listing) return <NotFound />;

  const fullAddress = `${listing.address}, ${listing.city}, ${listing.state} ${listing.zip}`;

  return (
    <div className="min-h-screen font-sans bg-warm-white">
      {/* PropSite banner */}
      <div className="bg-gold text-white text-center text-xs py-2 px-4 font-medium">
        This site was auto-generated by{" "}
        <Link href="/" className="underline font-bold">
          {PLATFORM_NAME}
        </Link>{" "}
        — a property website for every listing, automatically.
      </div>

      {/* Hero */}
      <div
        className="relative min-h-[480px] flex flex-col justify-end pb-12 px-6 text-white"
        style={
          listing.photoUrls && listing.photoUrls.length > 0
            ? {
                backgroundImage: `linear-gradient(to top, rgba(0,0,0,0.85) 0%, rgba(0,0,0,0.4) 50%, rgba(0,0,0,0.2) 100%), url(${listing.photoUrls[0]})`,
                backgroundSize: "cover",
                backgroundPosition: "center",
              }
            : { background: "linear-gradient(160deg, #1a2e1a 0%, #2d4a2d 40%, #3a5c3a 100%)" }
        }
      >
        <div className="max-w-[900px] mx-auto w-full">
          <p className="text-sm font-medium text-white/70 mb-2 uppercase tracking-wide">
            {listing.city}, {listing.state}
          </p>
          <h1 className="text-4xl md:text-5xl font-serif font-bold mb-4 leading-tight">
            {listing.address}
          </h1>
          <div className="inline-flex items-center bg-gold text-white px-5 py-2 rounded-full font-bold text-xl mb-6">
            {formatPrice(listing.price)}
          </div>
          <div className="flex flex-wrap gap-6 text-sm text-white/90">
            <span><strong className="font-semibold">{listing.beds}</strong> beds</span>
            <span><strong className="font-semibold">{listing.baths}</strong> baths</span>
            <span><strong className="font-semibold">{listing.sqft.toLocaleString()}</strong> sqft</span>
            <span><strong className="font-semibold">{listing.lotAcres}</strong> acres</span>
            <span>Built <strong className="font-semibold">{listing.yearBuilt}</strong></span>
            {listing.garage && <span>🚗 Garage</span>}
          </div>
        </div>
      </div>

      {/* Photo gallery */}
      {listing.photoUrls && listing.photoUrls.length > 1 && (
        <div className="max-w-[900px] mx-auto px-6 pt-8">
          <div className="grid grid-cols-2 md:grid-cols-3 gap-3">
            {listing.photoUrls.slice(0, 6).map((url, i) => (
              <a
                key={i}
                href={url}
                target="_blank"
                rel="noopener noreferrer"
                className="block aspect-[4/3] rounded-lg overflow-hidden bg-cream border border-border hover:opacity-95 transition-opacity"
              >
                <img
                  src={url}
                  alt={`${listing.address} photo ${i + 1}`}
                  className="w-full h-full object-cover"
                  loading="lazy"
                />
              </a>
            ))}
          </div>
          {listing.photoUrls.length > 6 && (
            <p className="text-center text-xs text-muted mt-3">
              + {listing.photoUrls.length - 6} more photo{listing.photoUrls.length - 6 !== 1 ? "s" : ""}
            </p>
          )}
        </div>
      )}

      {/* Main content */}
      <div className="max-w-[900px] mx-auto px-6 py-12">
        <div className="grid grid-cols-1 lg:grid-cols-[1fr_360px] gap-10">
          {/* Left */}
          <div>
            {/* Neighborhood scores */}
            <div className="mb-8">
              <h2 className="text-sm font-semibold text-muted uppercase tracking-wide mb-3">Neighborhood</h2>
              <div className="flex flex-wrap gap-2">
                <ScoreChip label="Walk" score={listing.walkScore} />
                <ScoreChip label="Bike" score={listing.bikeScore} />
                <ScoreChip label="Schools" score={listing.schoolRating * 10} />
                <ScoreChip label="Transit" score={listing.transitScore} />
              </div>
            </div>

            {/* Description */}
            <div className="mb-8">
              <h2 className="text-lg font-serif font-semibold text-ink mb-3">About this home</h2>
              <p className="text-muted leading-relaxed">{listing.description}</p>
            </div>

            {/* Details grid */}
            <div className="mb-8 border border-border rounded-lg overflow-hidden">
              <div className="bg-cream px-4 py-3 border-b border-border">
                <h2 className="text-sm font-semibold text-ink uppercase tracking-wide">Property Details</h2>
              </div>
              <div className="grid grid-cols-2 divide-x divide-border">
                {[
                  ["Bedrooms", listing.beds],
                  ["Bathrooms", listing.baths],
                  ["Living Area", `${listing.sqft.toLocaleString()} sqft`],
                  ["Lot Size", `${listing.lotAcres} acres`],
                  ["Year Built", listing.yearBuilt],
                  ["Garage", listing.garage ? "Yes" : "No"],
                ].map(([label, value], i) => (
                  <div key={i} className={`px-4 py-3 ${i % 2 === 0 ? "" : ""} border-b border-border last:border-b-0`}>
                    <p className="text-xs text-muted mb-0.5">{label}</p>
                    <p className="text-sm font-medium text-ink">{value}</p>
                  </div>
                ))}
              </div>
            </div>

            {/* Agent bar */}
            <div className="flex items-center justify-between p-4 border border-border rounded-lg bg-cream">
              <div>
                <p className="text-xs text-muted mb-0.5">Listed by</p>
                <p className="font-semibold text-ink text-sm">{listing.agentName}</p>
                <p className="text-xs text-muted">{listing.agentBrokerage}</p>
              </div>
              <div className="text-right">
                <p className="text-xs text-muted mb-0.5">Powered by</p>
                <p className="text-sm font-serif">
                  <span className="text-ink font-bold">{WORDMARK_PREFIX}</span>
                  <span className="text-gold font-bold">{WORDMARK_SUFFIX}</span>
                </p>
              </div>
            </div>
          </div>

          {/* Right — lead form */}
          <div className="lg:sticky lg:top-6 self-start">
            <div className="border border-border rounded-lg p-6 bg-white shadow-sm">
              <h3 className="font-serif font-semibold text-ink text-lg mb-1">Request a Showing</h3>
              <p className="text-xs text-muted mb-4">We'll connect you with the listing agent within 60 seconds.</p>
              <LeadForm listing={listing} />
            </div>

            <div className="mt-4 text-center">
              <Link href="/#demo" className="text-xs text-muted hover:text-ink transition-colors underline">
                ← Back to all examples
              </Link>
            </div>
          </div>
        </div>
      </div>

      {/* Footer watermark */}
      <div className="border-t border-border py-6 text-center text-xs text-muted">
        <span>
          Site auto-built by{" "}
          <Link href="/" className="font-semibold hover:text-gold transition-colors">
            <span className="text-ink">{WORDMARK_PREFIX}</span>
            <span className="text-gold">{WORDMARK_SUFFIX}</span>
          </Link>{" "}
          · {fullAddress}
        </span>
      </div>
    </div>
  );
}
