import { readFileSync } from "fs";
import { fileURLToPath } from "url";
import { dirname, join } from "path";
import { db, emailClickEventsTable } from "@workspace/db";
import { logger } from "../logger.js";

const log = logger.child({ component: "seed-click-events" });

interface SeedRow {
  token: string;
  agentEmail: string;
  listingId: string;
  linkType: string;
  destinationUrl: string;
  createdAt: string;
}

/**
 * One-time seed: imports click event tokens that were generated by the dev
 * environment (which drained the email outbox and sent cold outreach emails
 * before the outbox drain was restricted to production).
 *
 * Runs idempotently via ON CONFLICT DO NOTHING — safe to call on every boot.
 */
export async function seedClickEvents(): Promise<void> {
  const __filename = fileURLToPath(import.meta.url);
  const __dirname = dirname(__filename);
  const seedPath = join(__dirname, "clickEventsSeed.json");

  let rows: SeedRow[];
  try {
    const raw = readFileSync(seedPath, "utf8");
    rows = JSON.parse(raw) as SeedRow[];
  } catch {
    log.warn("No click events seed file found — skipping seed");
    return;
  }

  if (!rows.length) return;

  log.info({ count: rows.length }, "Seeding missing click events into DB");

  const BATCH = 500;
  let inserted = 0;

  for (let i = 0; i < rows.length; i += BATCH) {
    const batch = rows.slice(i, i + BATCH);
    const values = batch.map((r) => ({
      token: r.token,
      agentEmail: r.agentEmail,
      listingId: r.listingId,
      linkType: r.linkType as "preview" | "activate",
      destinationUrl: r.destinationUrl,
      clickedAt: null,
      createdAt: new Date(r.createdAt),
    }));

    await db
      .insert(emailClickEventsTable)
      .values(values)
      .onConflictDoNothing();

    inserted += batch.length;
  }

  log.info({ inserted }, "Click events seed complete");
}
